-- 고양이와 개는 몇 마리 있을까
SELECT
    ANIMAL_TYPE, COUNT(ANIMAL_ID) as count
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

-- 동명 동물 수 찾기
SELECT
    NAME, COUNT(NAME) 
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME

-- 입양 시각 구하기(1)
SELECT
    CAST(SUBSTR(DATETIME, 12 , 2) as UNSIGNED) as HOUR, COUNT(*)
FROM ANIMAL_OUTS
WHERE SUBSTR(DATETIME, 12 , 2) BETWEEN '09' and '19'
GROUP BY HOUR
ORDER BY HOUR

-- 입양 시각 구하기(2)
WITH RECURSIVE num AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n + 1 FROM num WHERE n < 23
) 

SELECT n, ifnull(cnt, 0)
FROM num as A LEFT OUTER JOIN (
    SELECT
    CAST(SUBSTR(DATETIME, 12, 2) as UNSIGNED) as HOUR, COUNT(*) as cnt
    FROM ANIMAL_OUTS
    GROUP BY HOUR) as B
ON A.n = B.HOUR